<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Комп\'ютерна діагностика']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масла в двигуні']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'планове техобслуговування']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масла в двигуні зі зняттям захисту']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Діагностика течі масла']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масляного фільтра']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масла з промиванням двигуна']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Діагностика течі О / Ж']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна повітряного фільтра двигуна']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна рідини ГУР']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна фільтра паливного підвісного']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масла ГУР']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масло Haldex']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна фільтра паливного в баку']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Перевірка рівня масла в АКПП']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна ременя ГУР']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна фільтра палива дизельного']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Промивання системи охолодження']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна ременя генератора']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масла в роздавальної коробці']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масла в мосту']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна рідини системи охолодження']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна ременя кондиціонера']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна ролика натяжної ременя поліклинового']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна ролика обвідного ременя поліклинового']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна повітряного фільтра салону']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна масла в КПП']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна охолоджуючої рідини']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна ременя ГРМ']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна ременя поліклинового']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна приводного ременя']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна роликів ГРМ']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна комплекту ременя ГРМ з роликами і водяний помпою']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Заміна роликів приводу']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'промивання двигуна']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Комплексна діагностика автомобіля']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Перевірка та долив технічних рідин']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Первинний огляд автомобіля']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Регулярний огляд автомобіля']);
        DB::table('service_items')->insert(['service_id' => 1,'title' => 'Долив масла КПП']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Діагностика гальмівної системи']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна датчика ABS']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна клапана вакуумного насоса']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Прокачування гальмівної системи']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна гальмівного барабана з підшипником']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна колодок ручного гальма']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна гальмівного супорта']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна ремкомплекта гальмівного супорта']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна передніх гальмівних колодок']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна задніх гальмівних колодок']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна гальмівної рідини']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна задніх гальмівних дисків']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна передніх гальмівних дисків']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна барабанних колодок']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна гальмівних барабанів']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна гальмівного шланга']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна троса ручного гальма']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна головного гальмівного циліндра']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна робочого гальмівного циліндра']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна вакуумного підсилювача гальм']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна циліндра гальмівного супорта']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна захисту диска']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Перевірка ступеня зносу гальмівних колодок']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна троса гальма стоянки']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна гальмівних колодок гальма стоянки']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна датчика зносу гальмівних колодок']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна скоби гальмівного супорта']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна направляючих супорта гальмівного']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна гальмівної трубки']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Обслуговування гальмівної системи']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Обслуговування супорта гальмівного']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Заміна заднього гальмівного циліндра']);
        DB::table('service_items')->insert(['service_id' => 2,'title' => 'Профілактика гальмівних колодок (дискових)']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Повна діагностика автомобіля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Предпокупочная діагностика автомобіля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Діагностика ходової частини автомобіля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Діагностика стуку підвіски']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна всіх с / б підвіски']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна задніх важелів']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна пильовика кульової опори']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'заміна маточини']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка заднього важеля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка задньої балки']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка моста']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка переднього важеля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка підрамника']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка стабілізатора']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна сайлентблоков важеля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна важеля поздовжнього']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна переднього важеля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна підвісної подшініка']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна сайлентблока плаваючого']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна подушки двигуна']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна сайлентблоков підрамника']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'заміна Пневмоамортизатор']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна сальника півосі']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна підшипника маточини']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна передніх амортизаторів']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна задніх амортизаторів']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна кульової опори']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна втулки стабілізатора']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна стійки стабілізатора']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна опори передньої стійки']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'виготовлення сайлентблоков']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка підшипника маточини']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'заміна сайлентблоков']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна рульового наконечника']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна верхньої опори амортизатора']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка передніх амортизаторів']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'заміна відбійників']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка ресор']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка задніх амортизаторів']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка важеля']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна підшипника опори амортизатора']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна сервісного комплекту амортизатора']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна важеля підвіски']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна підшипника піввісь']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'заміна підрамника']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна сайлентблоков ресор']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Зняття-установка передньої піввісь']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна відбійників ресор']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна наконечника рульової тяги']);
        DB::table('service_items')->insert(['service_id' => 3,'title' => 'Заміна передніх важелів']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Діагностика рульового управління']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна бачка ГУР']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна насоса ГУР']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Ремонт шланга ГУР']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Зняття-установка-ремонт насоса ГУР']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Зняття-установка-ремонт трубки ГУР']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна пильовика кермової рейки від 462 грн']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна рульової рейки і насоса від 693 грн']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Ремонт рульової рейки і насоса']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Ремонт електропідсилювача керма']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна рідини ГУР']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна рульової тяги']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна пильовика кермової тяги']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна рульового наконечника']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна елементів рульового управління']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Заміна хрестовини рульового вала']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Зняття / встановлення рульового вала']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Зняття-установка рульової рейки']);
        DB::table('service_items')->insert(['service_id' => 4,'title' => 'Зняття-установка насоса ГУР']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'діагностика двигуна']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна бачка вентиляції картера']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'заміна ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна клапана охолодження поршня']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна клапана турбіни']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна подушки ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна поршневих кілець']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'заміна поршня']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладки клапана VVT']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладки турбіни']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладок двигуна']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна сальників ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'заміна теплообмінника']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Замір компресії']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Переклеювання верхньої плити ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладки впускного колектора']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'переклеювання піддона']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладки клапанної кришки']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Розбирання-збірка ГБЦ']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття / встановлення турбіни']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'ремонт Вебасто']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна шківа коленвала']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна заднього сальника коленвала']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття-установка вентилятора ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття-установка ГБЦ']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття-установка двигуна']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття-установка піддону']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття-установка теплообмінника']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття-установка термостата']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Чистка клапана распредвала випуск']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'шліфування ГБЦ']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна водяної помпи']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'заміна турбіни']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Капітальний ремонт двигуна']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Ремонт головки блоку циліндрів (ГБЦ)']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'заміна термостата']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна радіатора охолодження']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладки блоку циліндрів (ГБЦ)']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна ланцюга ГРМ']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'ремонт турбіни']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна датчика коленвала і распредвала']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна опори ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна сальника розподільного']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна сальника коленвала']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Регулювання клапанів']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Зняття-установка впускного колектора']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Очищення патрубків системи циркуляції повітря']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладки випускного колектора']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна випускного колектора']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'діагностика турбіни']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна прокладки передньої кришки двигуна']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна піддону ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Перегерметізація піддону ДВС']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна штовхача клапана']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна ущільнювального кільця форсунки']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Діагностика стану ременя і роликів приводу (навісного обладнання)']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна переднього сальника коленвала']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Перегерметізація фільтра системи вентиляції картера']);
        DB::table('service_items')->insert(['service_id' => 5,'title' => 'Заміна комплекту ременя ГРМ з роликами']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Діагностика паливної системи']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Зняття-установка форсунок']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Ремонт уприскування дизельних систем']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'ремонт інжектора']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Промивання системи упорскування']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна паливного фільтра']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна бензинової форсунки']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна дросельної заслінки']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Чистка форсунок двигуна']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна бензонасоса підвісного']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна бензонасоса погружного (в баку)']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Замір тиску паливного насоса']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Частка паливної системи']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна паливного насоса']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна паливного бака']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Промивання паливного бака']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Частка дизельних форсунок']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'чистка інжектора']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Ремонт бензинової форсунки']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Ремонт дизельних форсунок']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна дизельних форсунок']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Ремонт паливного насоса високого тиску (ТНВД)']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Чистка дросельної заслінки']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Чистка бензинових форсунок']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Заміна клапана адсорбера']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Полірування регулювальних шайб']);
        DB::table('service_items')->insert(['service_id' => 6,'title' => 'Діагностика тиску паливної системи']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'діагностика електрики']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна датчика тиску палива']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна датчика кута повороту керма']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна мотора склоочисників (двірників)']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна свічок розжарювання']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'діагностика акумулятора']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Зняття / встановлення колектора']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна свічок запалювання']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'ремонт генератора']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'заміна генератора']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна акумуляторної батареї']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна акумулятора (під капотом)']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна акумулятора (в багажнику)']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна акумулятора (під сидінням)']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'заміна стартера']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'заміна автолампочек']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна датчика тиску']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна замка запалювання']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна високовольтних проводів']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Зняття-установка генератора']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Зняття-установка замку запалювання']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Діагностика системи запалювання']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Зняття-установка стартера']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Заміна противотуманной фари']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'підключення дзеркала']);
        DB::table('service_items')->insert(['service_id' => 7,'title' => 'Перевірка стану свічок запалювання']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'Діагностика вихлопної системи']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'заміна глушника']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'Зняття-установка фільтр сажі']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'Заміна лямбда-зонда']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'заміна каталізатора']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'установка пламегасителя']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'Заміна фільтру сажі']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'ремонт глушника']);
        DB::table('service_items')->insert(['service_id' => 8,'title' => 'Ремонт вихлопної системи']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'діагностика зчеплення']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Заміна головного циліндра зчеплення']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Заміна двомасових маховика']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Регулювання троса зчеплення']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Заміна комплекту зчеплення']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Долив гідравлічної рідини зчеплення']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Заміна робочого циліндра зчеплення']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Заміна троса зчеплення']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Заміна вичавного підшипника']);
        DB::table('service_items')->insert(['service_id' => 9,'title' => 'Заміна вилки зчеплення']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'діагностика трансмісії']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Зняття-установка КПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна опори КПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'балансування кардана']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна проміжного підшипника']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна пильовика кардана']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна радіатора АКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'заміна хрестовини']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна кронштейна АКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна сальників АКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Зняття-установка кардана']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Зняття-установка роздавальної коробки']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'ремонт АКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'ремонт МКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Ремонт редуктора переднього моста']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Ремонт редуктора заднього моста']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Ремонт роздавальної коробки']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'заміна АКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'заміна МКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна масла АКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна масла МКПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'заміна півосі']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна пильовика ШРУС']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'заміна ШРУС']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна масла в елементах трансмісії']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна сальників піввісь']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна підвісної підшипника']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Ремонт важеля КПП']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Заміна редуктора заднього моста']);
        DB::table('service_items')->insert(['service_id' => 10,'title' => 'Зняття / встановлення редуктора']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Заміна амортизаторів багажника']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Заміна бачка омивача']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'заміна габариту']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Заміна заднього ліхтаря']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Заміна переднього підрамника']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Заміна передньої фари']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'заміна поворотника']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Заміна троса капота']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'заміна емблеми']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Зняття-установка заднього бампера']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Зняття-установка переднього бампера']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Зняття-установка паливного бака']);
        DB::table('service_items')->insert(['service_id' => 11,'title' => 'Заміна амортизатора капота']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'установка ксенону']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'установка сигналізації']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'установка аудіосистеми']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'Установка захисту двигуна']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'установка парктроника']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'установка фаркопа']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'Зняття / встановлення захисту двигуна']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'Зняття-установка кнопки склопідйомники']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'Заміна щітки склоочисника']);
        DB::table('service_items')->insert(['service_id' => 12,'title' => 'заміна стеклопод\'емника']);
    }
}
